name: Build Docker Image, Scan and Release

on:
  push:
    branches:
      - "release-please--branches--main--components--release-please-action"
#      - "main"
#    paths:
#      - "CHANGELOG.md"
  workflow_dispatch:


jobs:
  test:
    uses: telicent-oss/shared-workflows/.github/workflows/python-ci-qa.yml@main
    with:
      PYTHON_VERSION: "3.12"
      SKIP_BUILD: true

  get-version:
    uses: telicent-oss/shared-workflows/.github/workflows/python-get-version-number.yml@main

  build-docker-version:
    uses: telicent-oss/shared-workflows/.github/workflows/python-push-to-registries.yml@CORE-248-smart-cache-paralog-api-opensource
    needs:
      - test
      - get-version
    with:
      APP_NAME_PREFIX: ""
      APP_NAME: paralog-api
      DOCKERFILE: Dockerfile
      PATH: ./
      VERSION: ${{ needs.get-version.outputs.version }}
    secrets: inherit

  do-github-release:
    name: Do GitHub Release
    uses: telicent-oss/shared-workflows/.github/workflows/python-gh-release.yml@main
    needs:
      - get-version
      - build-docker-version
    with:
      VERSION: ${{ needs.get-version.outputs.version }}

  attach-sboms-to-release:
    name: Attach SBOMs to release
    needs:
      - do-github-release
      - get-version
      - build-docker-version
    strategy:
      matrix:
        sbom-artifacts:
         - ${{ needs.build-docker-version.outputs.image-sbom-artifact-name }}
         - ${{ needs.build-docker-version.outputs.application-sbom-artifact-name }}
    uses: telicent-oss/shared-workflows/.github/workflows/python-attach-sbom-to-release.yml@main
    with:
      SBOM_ARTIFACT: ${{ matrix.sbom-artifacts }}
      VERSION: ${{ needs.get-version.outputs.version }}