name: Python Tests

on:
#  pull_request:
#    branches:
#      - "release-please*"
#  push:
#    branches-ignore:
#      - "main"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
    uses: telicent-oss/shared-workflows/.github/workflows/python-ci-qa.yml@main
    with:
      PYTHON_VERSION: ${{ matrix.python-version }}
      SKIP_BUILD: true