name: Python Vuln Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  scan-pr:
    uses: telicent-oss/shared-workflows/.github/workflows/python-generate-and-scan-application.yml@main
    with:
      SCAN_NAME: ${{ github.run_number }}

  scan-dockerfile:
    name: Scan Dockerfile
    uses: telicent-oss/shared-workflows/.github/workflows/trivy-dockerfile-scan.yml@main
    with:
      SCAN_NAME: ${{ github.run_number }}-dockerfile
      DOCKERFILE: Dockerfile